### ISSUE TITLE
User Permissions

### ISSUE THREAD

**Issue by petecog** [alephinsights/prj-stratus#9]
We need to work out a 'permissions model'. 

- what permissions do users need?
- Who can assign them?
- Azure groups - what's the structure we want?

**Comment by S010MON** [comment]
Potential set:

1. **User**: Can start/stop VMs
2. **Provisioner**: Can provision VMs and add them to the network (using readme file here/ACA instructions).  Will need Jumpcloud permissions too for adding new devices.
3. **Admin**: Full Sub/Res Gp/Net rights
